### PR TITLE
Update circleci configuration to 2.0

### PR DESCRIPTION
**Pull request by j0ni**
Example green build [here](https://circleci.com/gh/j0ni/test.chuck/5).

### CODE REVIEW

**Comment by gfredericks** [comment]
This is really cool, thanks!

Is installing node manually necessary because circleci is unlikely to have a mechanism for having both clojure and node available?

**Comment by j0ni** [comment]
There is a `node` available to install using `apt` but it's quite old, and I wanted to use current stable (if it passed :)), which is 10.x.

This was the quickest route to green, but there might be nicer ways to organize it, so you could have something like a matrix, using Circle's workflows - include jobs which run on images with different versions of node and java (say).

There may also be images out there which maintain a node+java+leiningen environment. I didn't find one but I didn't look very hard.

**Comment by gfredericks** [comment]
Cool -- well I'm just happy to have it working, so this is great. Thanks again

**Comment by j0ni** [comment]
You are most welcome :)

**Comment by gfredericks** [comment]
And thanks yet again, because I was recently able to reuse this without any trouble for [schema](https://github.com/plumatic/schema) and [schema-generators](https://github.com/plumatic/schema-generators).

**Pull request merged**
