### PR TITLE
Fix build, bump deps, support `times` in cljs

### PR DESCRIPTION
**Pull request by frenchy64**
Going out on a limb that this is a welcome change, but I saw the build has been broken for a while and PR's don't automatically run CI.

I took the opportunity to design a matrix build in Actions that uses `times` with different multipliers. Seems like a nice demo of its intended usage.

I noticed it's easy to support `times` in cljs too, so I added it.

### CODE REVIEW

**Comment by gfredericks** [comment]
oh man I had almost considered tweeting about this to see if anybody knew how to fix it

thanks!

**Comment by gfredericks** [comment]
Released as `0.2.12`

**Comment by frenchy64** [comment]
Thanks!

**Comment by gfredericks** [comment]
(incidentally, the build is still failing, though in a different way than before; maybe there's a change I have to make on circleci?)

**Comment by frenchy64** [comment]
Yes, you need to stop CircleCI building this repo. Something like https://support.circleci.com/hc/en-us/articles/360021666393-How-to-stop-building-by-manually-removing-the-CircleCI-webhook-and-deploy-key-from-your-GitHub-repository

**Comment by gfredericks** [comment]
oh, you switched it to...github actions?

**Comment by frenchy64** [comment]
Shame on me for not making that more obvious, but yes! Happy to figure out how to build with CircleCI if that's a problem.

**Comment by gfredericks** [comment]
oh no it's fine -- I just assumed it was so radically different because circleci had made a bunch of changes

do I need a different badge in the README, or is the build status automatically displayed somewhere so I should just delete the circleci one?

**Comment by frenchy64** [comment]
:) Yes, delete the CircleCI badge.

If you want a badge, see [here](https://docs.github.com/en/actions/managing-workflow-runs/adding-a-workflow-status-badge), though it doesn't seem to add much to me.

**Comment by gfredericks** [comment]
Perfect, thanks again!

**Pull request merged**
