### PR TITLE
Resolves #39: Added cljs support for `times`

### LINKED ISSUE #39: `times` function not available in clojurescript
The `times` function is not available in clojurescript. I'm happy to provide a PR to address that if there is no issue.

Thank you.

### PR DESCRIPTION
**Pull request by sandhu**
The multiplication factor is always 1 in cljs.

### CODE REVIEW

**Comment by gfredericks** [comment]
oh, that docstring is on a private function -- I was thinking of the docstring on `times` in particular so that users can tell what it's (not) going to do.

**Comment by sandhu** [comment]
You're right. I will fix it and push.

**Comment by gfredericks** [comment]
Looks good, thanks!

**Comment by gfredericks** [comment]
Released in `0.2.2`.

**Comment by sandhu** [comment]
Thank you. Very much appreciated

**Pull request merged**
